### ISSUE TITLE
Modal footer top margin

### ISSUE THREAD

**Issue by nickroberts** [PBGUX/pb-design-system#32] opened 2017-07-17 16:09 UTC
In order to make sure spacing is consistent between the modal header, body and footer, we should have the same margins.

Right now, the header has a bottom padding of 10px, then a border, then a 30px bottom margin.

The footer has a top margin of 40px.

I understand the thought process (as I did the same), but in order to see the spacing consistent, we should have the margin-top for the modal footer be 30px (to keep the same spacing between the border of the header and the body, along with the body and the footer).

I was looking at SendPro trying to figure it out, then I saw the margins in DS.

Hope this makes sense!

**Comment by smlombardi** [comment] 2017-07-17 16:42
I will look into making them the same, likely both 30px.

Please not that in "design world", we are taught that things look more centered if there is actually more space on the bottom.  Often when the space is the same, the content looks "low".

**Comment by nickroberts** [comment] 2017-07-17 17:06
Totally understandable.

**Comment by danielcollettepb** [comment] 2017-08-09 18:39
@smlombardi is a story created for this? If not, please create and close this issue.

**Comment by smlombardi** [comment] 2017-08-09 18:50
This is not a bug, it is by design

**Closed by smlombardi** 2017-08-09 18:50 UTC
Labels: bug
